### ISSUE TITLE
Multiple add_*_layer of same type (*) possible? 

### ISSUE THREAD

**Issue by kelprmy** [crazycapivara/mapboxer#69]
Hi! 
When I'm trying to add multiple local point layers by first using as_mapbox_source() and then add_circle_layer, only the first layer shows... Any idea on how to solve this? 
Best, Guri

**Comment by crazycapivara** [comment]
@kelprmy do you want to show different layers for the same source? Please provide a simple code snippet.

**Comment by crazycapivara** [comment]
See also [Prepare reprexes](https://reprex.tidyverse.org/)

**Comment by kelprmy** [comment]
> @kelprmy do you want to show different layers for the same source? Please provide a simple code snippet.

Will add simple code snippet later, but didn't have time right now. The layers are from two different sources, basically just two different data.frames with lat, long, and a couple of columns with properties.

**Comment by kelprmy** [comment]
Seems to be working fine now, after restarting R :) Haven't been able to reproduce the problem. Don't know why, though ...
