### ISSUE TITLE
Filter on multiple 

### ISSUE THREAD

**Issue by kelprmy** [crazycapivara/mapboxer#70]
Hi,
I've tried for a while to figure out the syntax for filtering on multiple string-values in mapboxer. The syntax in mapboxer/mapbox is very unfamiliar to me (strictly an R-user with background as a biologist). I am sorry if this is a stupid question to post, but I'm really stuck ...

# **Example:**
```R
require(tidyverse)
require(mapboxer)

#### Show "all" data (ex 1)
motor_vehicle_collisions_nyc %>%  
  mutate(brand = rep_len(c("Aissan", "Besla", "Coyota", "Dolvo"), 
                         length.out = dim(.)[1])) %>%
  mutate(color = rep_len(c("blue", "green", "red", "yellow"), 
                         length.out = dim(.)[1])) %>% 
  dplyr::filter(injured > 1) %>%
  as_mapbox_source() %>%
  mapboxer(
    center = c(-73.9165, 40.7114),
    zoom = 9
  ) %>%
  add_circle_layer(circle_color = c("get", "color"))

#### Filter on one brand (ex 2)
motor_vehicle_collisions_nyc %>%  
  mutate(brand = rep_len(c("Aissan", "Besla", "Coyota", "Dolvo"), 
                         length.out = dim(.)[1])) %>%
  mutate(color = rep_len(c("blue", "green", "red", "yellow"), 
                         length.out = dim(.)[1])) %>% 
  dplyr::filter(injured > 1) %>%
  as_mapbox_source() %>%
  mapboxer(
    center = c(-73.9165, 40.7114),
    zoom = 9
  ) %>%
  add_circle_layer(circle_color = c("get", "color"),
                   filter = list("==", "brand", "Besla"))

#### To filter on multiple brands I could of course do (ex 3)
motor_vehicle_collisions_nyc %>%  
  mutate(brand = rep_len(c("Aissan", "Besla", "Coyota", "Dolvo"), 
                         length.out = dim(.)[1])) %>%
  mutate(color = rep_len(c("blue", "green", "red", "yellow"), 
                         length.out = dim(.)[1])) %>% 
  dplyr::filter(brand %in% c("Aissan", "Besla")) %>% 
  dplyr::filter(injured > 1) %>%
  as_mapbox_source() %>%
  mapboxer(
    center = c(-73.9165, 40.7114),
    zoom = 9
  ) %>%
  add_circle_layer(circle_color = c("get", "color"))
```

But, if I need to filter on multiple brands from an actual mapbox source, the last example (ex 3) is not an option. I would like to know how to specify that in ex 2. What should the syntax in the filter look like to include more than one brand? (I've tried stuff from the mapbox expressions documentation, but I don't think I've got the syntax right, and there is no error message telling me what is wrong, so I'm completely lost ...)
Hope you can point me in the right direction.
Best,
Guri

**Comment by crazycapivara** [comment]
@kelprmy I also had the inension to add some helper functions for creating the right syntax, because if you are not used to it, it sometimes might be difficult to create the correct expression.

First you put in the function/operator and then its arguments, in your case the function is `in`:

```r
filter <- list("in", "brand", "Aissan", "Besla")
```

See also [filter-multiple-example](https://github.com/crazycapivara/mapboxer/blob/master/examples/filter-multiple.R)

**Comment by crazycapivara** [comment]
In case you want to filter on more the one property, you do it like this:

JavaScript:

```javascript
filter = ["all", ["in", "brand", "A", "B"], ["==", "injured", 1]]
```
And the pendant in R:

```r
filter <- list(
  "all",
  list("in", "brand", "A", "B"),
  list("==", "injured", 1)
)
```

**Comment by kelprmy** [comment]
You are completely awesome, @crazycapivara !! :)
