### ISSUE TITLE
Add legend control to main branch?

### ISSUE THREAD

**Issue by sharlagelfand** [crazycapivara/mapboxer#80]
Hi there! Thanks for this great package - super useful and easy to use!

I was looking into adding a legend to a map and noticed you have a PR merged for this, #53, but it's only been merged into the `develop` branch. Just curious if you had plans to integrate this into the main branch or if there's some reason it's been left as a development feature.

Thanks!

**Comment by crazycapivara** [comment]
Hi @sharlagelfand,
yes it should be integrated in the main branch. It is not merged yet, because I added more features to develop and I need to clean the code and update docs before merging it to the main branch. Hope I will find time for it soon. But until then you can use the develop branch.

**Comment by sharlagelfand** [comment]
Thank you! Wasn't sure just given the timing, but I know it's tough to find time for this stuff :) Thank you again!
