### ISSUE TITLE
How to add a geocoder?

### ISSUE THREAD

**Issue by hongyuanjia** [crazycapivara/mapboxer#84]
Thanks for this great package! It's quite easy to use. I searched through the manual but did not find a way to add a [geocoder](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/). Could you provide some insights? Thanks.

**Comment by crazycapivara** [comment]
Hi @hongyuanjia The geocoder is a plugin, which is not yet included in the `mapboxer` package (yet).
But there is possibility to include it adding the dependency with the hidden function `mapboxer:::add_deps()` in conjunction with `htmlwidgets::onRender()` passing JavaScript code:

```r
Sys.setenv(MAPBOX_API_TOKEN = "<your-api-key>")

geocoder_plugin <- htmltools::htmlDependency(
  name = "geocoder",
  version = "4.7.2",
  src = c(href = "https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.2"),
  script = "mapbox-gl-geocoder.min.js",
  stylesheet = "mapbox-gl-geocoder.css"
)

mapboxer() %>%
  mapboxer:::add_deps(list(geocoder_plugin)) %>%
  htmlwidgets::onRender(
    "function(el, x) {
       const map = mapboxer._widget[el.id].map;
       const geocoder = new MapboxGeocoder({
         accessToken: mapboxgl.accessToken,
         mapboxgl: mapboxgl
       });
       map.addControl(geocoder);
     }"
  )
```

**Comment by hongyuanjia** [comment]
Thanks, @crazycapivara ! It works like a charm!

Close it now.
