### ISSUE TITLE
Typo in satellite streets basemap name

### ISSUE THREAD

**Issue by psolymos** [crazycapivara/mapboxer#87]
Hello, I noticed that a letter is missing here:

```R
> basemaps$Mapbox$satellite_steets_v11
[1] "mapbox://styles/mapbox/satellite-steets-v11"
```

The link should be `mapbox://styles/mapbox/satellite-streets-v11` (`streets` not `steets`).

Thanks!

**Comment by crazycapivara** [comment]
@psolymos THanx. I will fix it.
